### ISSUE TITLE
DSN Format

### ISSUE THREAD

**Issue by paragonie-scott** [paragonie/pco_prototype#2]
Since we are using DSN-like strings for the constructor, we should decide how they behave.

* `":cipher=AES-256;mode=GCM"` should use whatever driver allows `aes-256-gcm` or throw an exception if none are available
* `"openssl:cipher=AES-256;mode=GCM"` should use specifically openssl for `aes-256-gcm`, and throw an exception if `openssl` is not installed
* `"libsodium"` should use libsodium (or throw an exception if it's not installed) in the default configuration
* `"openssl"` should use openssl in a secure, sane default
* `"openssl:cipher=AES-128;mode=ECB"` should throw an exception because we do not allow secure modes
* `"openssl:cipher=AES"` should use `aes-128-ctr` with `HMAC-SHA-256`
* `"openssl:cipher=AES-128;hash=SHA256"` should use `aes-128-ctr` with `HMAC-SHA-256`

Thoughts or contrary positions are welcome.

**Comment by AshleyPinner** [comment]
@ircmaxell What about making it assume you want AES-128 and throw a notice?

**Comment by ircmaxell** [comment]
I wouldn't raise a notice. If we want to default to AES-128, that's fine. Just make that the default.

**Comment by paragonie-scott** [comment]
Updated the OP. I agree that AES should map to AES-128 since simply "openssl" is a sane default.
