### ISSUE TITLE
Constructor

### ISSUE THREAD

**Issue by paragonie-scott** [paragonie/pco_prototype#4]
Should we ditch the DSN and just accept an array instead? i.e.

```php
$AES = new \PCO\Symmetric([
    'driver' => 'openssl',
    'cipher' => 'aes-128'
]);
```

**Comment by redragonx** [comment]
Arrays may be easier to read in the long run. What about using JSON if we made some sort of custom parser?

**Comment by enygma** [comment]
+1 on the array personally...no extra overhead of extra parsing just for the sake of it. I could see allowing both in the future though, just for convenience.

**Comment by paragonie-scott** [comment]
Okay, that's what I'll go with then.
