### ISSUE TITLE
Allow AES-ECB for decryption only if it has a valid HMAC

### ISSUE THREAD

**Issue by AshleyPinner** [paragonie/pco_prototype#6]
As per title, if someone is migrating away from using AES-ECB, they should be allowed to decrypt their data with PCO, under the intention that encrypting it with PCO would not let them go back to ECB.

The restriction of requiring a HMAC is a general good idea (since unauthenticated crypto is a bad thing).

**Comment by paragonie-scott** [comment]
Now that I've had time to think about this, I'm inclined to say :-1:. If you were previously using AES-ECB, you should use your existing code to decrypt data before re-encrypting with our interface. If we take on the responsibility of data migrations, we open ourselves up to downgrade attacks.
